### ISSUE TITLE
Unable to determine the volume id for devices outside of xvd[a-f] range

### ISSUE THREAD

**Issue by ajjl** [alestic/ec2-consistent-snapshot#108]
This appears to be a result of this line here: https://github.com/alestic/ec2-consistent-snapshot/blob/master/ec2-consistent-snapshot#L508
Though I am not familiar with the code base so that might not be the only place where this happens. Is there a reason for this? Is the fix just as simple as opening up that regex?

Attempting to use this tool on a device on one of my instances results in this error: `ERROR: Unable to determine volume id for device xvdg1 in mount /home Usage: ec2-consistent-snapshot`

Thanks!

**Comment by ajjl** [comment]
@marcopin

**Comment by ajjl** [comment]
@macropin

**Comment by macropin** [comment]
I opened up the regex for LVM devices and it works fine.

**Comment by ehammond** [comment]
Thanks for submitting this. Unfortunately, this project is no longer under development in this repo. Anybody is welcome to fork the project and continue development if there is interest.
