### ISSUE TITLE
feature request: Ability to run remotely (i.e., not install on all db servers)

### ISSUE THREAD

**Issue by ledjon** [alestic/ec2-consistent-snapshot#15]
Any idea what it would take to change this so it can be run remote to the db server.  That is, the script (ec2-consistent-snapshot) sits on some centralized system and it can be used to do snap's for a lot of systems.

The only thing I can think that would need to be implemented is an ssh wrapper for physically connecting to the host to do the fsfreeze/unfreeze commands.  The rest of these are by design remote calls already.

Thoughts?

**Comment by ehammond** [comment]
I'm going to close this as there are no plans to implement it, but if somebody submits a *clean* way to do it, I'll certainly take a look. I'm also happy to discuss proposed approaches before anybody goes of and spends development time on it.
