### ISSUE TITLE
Snapshot doesn't get created for MongoDB when fsynclock takes > 30 seconds

### ISSUE THREAD

**Issue by bhang** [alestic/ec2-consistent-snapshot#16]
I'm trying to run the script against a MongoDB hidden secondary and it's taking > 30 seconds to fsync lock. The script exits cleanly but fails to create the snapshot. This is the output of debug:

    ec2-consistent-snapshot: Using AWS access key: xxxxxxx
    ec2-consistent-snapshot: Using description 'mongo backup - initial' for all snapshot descriptions
    ec2-consistent-snapshot: Mon Jul 29 19:50:57 2013: mongo connect on localhost:27017
    ec2-consistent-snapshot: Mon Jul 29 19:50:57 2013: locking mongo
    recv timed out (30000 ms) at /usr/local/lib/perl/5.14.2/MongoDB/Cursor.pm line 161.
    ec2-consistent-snapshot: Mon Jul 29 19:51:27 2013: unlocking mongo
    ec2-consistent-snapshot: Mon Jul 29 19:51:43 2013: mongo unlocked
    ec2-consistent-snapshot: Mon Jul 29 19:51:43 2013: done

I can get it to work if I modify the script to add this in mongo_connect():
`$MongoDB::Cursor::timeout = 60000;`

Maybe a command line option could be added to set/override this timeout value?
I'm not sure if this is the right place to be doing this though. Your input is appreciated.

**Comment by ehammond** [comment]
If somebody understands the issue here and cares enough to submit a patch, I will review.
