### ISSUE TITLE
feature request: add support for version info

### ISSUE THREAD

**Issue by neurogenesis** [alestic/ec2-consistent-snapshot#38]
to better support production environments, and ensure the correct / latest version of the snapshot and expire scripts are installed, it would be helpful to include the version in the following areas:

- an option provided to the cmd (-v and --version and added to -h)
- as part of stdout so version info can be captured in logs
- tagged in git (vX.X.X, i.e. v2.1.4)
- versioned in the package management repos (deb)

the last will help ops deploy a specific version to production environments from whatever provisioning tool is used (puppet / chef / os package manager).

**Comment by PortableTech** [comment]
I ran across this annoyance myself, in the end my solution was to use the following command to check the version since I am using your package version.

apt-show-versions ec2-consistent-snapshot
