### ISSUE TITLE
ec2-consistent-snapshot not working on new eu-central-1 region (Frankfurt)

### ISSUE THREAD

**Issue by return1** [alestic/ec2-consistent-snapshot#47]
i just migrated a few instances to the new AWS data center in Frankfurt. However, ec2-consistent-snapshot and ec2-expire-snapshots with provided region `--region eu-central-1`:

*ec2-consistent-snapshot: ERROR: create_snapshot: AuthFailure: AWS was not able to validate the provided access credentials at /usr/bin/ec2-consistent-snapshot line 295.*

*ec2-expire-snapshots: ERROR: describe_snapshots: HTTP POST FAILURE: 500 Can't connect to eu-central-1.ec2.amazonaws.com:443 at /usr/bin/ec2-expire-snapshots line 178.*

I am able to take snapshots with boto with identical credentials, so they are not the problem.

**Comment by sage-andrew-taylor** [comment]
It's to do with eu-central requiring requests be signed with the v4 signature. This is not currently supported in the underlying Perl EC2 module.

https://rt.cpan.org/Public/Bug/Display.html?id=99779

**Comment by ehammond** [comment]
Looks like this will need to be fixed in the external module.

**Comment by talisto** [comment]
I've created a fork that I've modified to use the `AWS CLI` tool instead of the `Net::Amazon::EC2` module, you're welcome to give it a try instead: https://github.com/talisto/ec2-consistent-snapshot

**Comment by mdai843** [comment]
I've created a fork of the Net::Amazon::EC2 module that uses AWS::Signature4 to sign requests. I'm not an expert in perl scripting so obviously use at your own discretion. I've been able to use the consistent snapshot script and the snapshot pruning script without modification in eu-central-1 after installing my modified module: https://github.com/mdai843/net-amazon-ec2

**Comment by jsandeo** [comment]
I fixed this by installing the Net::Amazon::EC2 Perl module [version 0.30_1](http://search.cpan.org/~mallen/Net-Amazon-EC2-0.30_1/lib/Net/Amazon/EC2.pm) (currently a development version).

I also had to patch the ec2-consistent-snapshot script to make it work with the new() method's new parameters "signature_version" and "region":

```perl
  # EC2 API object
  return Net::Amazon::EC2->new(
    ((! $use_iam_role) ? (AWSAccessKeyId  => $aws_access_key_id,) : () ),
    ((! $use_iam_role) ? (SecretAccessKey => $aws_secret_access_key) : () ),
    signature_version => 4,
    ($region ? (region => $region) : ()),
    ($ec2_endpoint ? (base_url => $ec2_endpoint) : ()),
    ($Debug ? (debug => 1) : ()),
  );
```
