### ISSUE TITLE
Add support for the non-blocking SHOW SLAVE STATUS

### ISSUE THREAD

**Issue by solomonty** [alestic/ec2-consistent-snapshot#48]
SHOW SLAVE STATUS is causing the slave to hang and to need to be restarted.

Please add an option to use the non-blocking versions of SHOW SLAVE STATUS for Percona versions 5.5 and 5.6 and MySQL version 5.7.

Please see these bug reports for more details of the issues with SHOW SLAVE STATUS

https://bugs.launchpad.net/percona-server/+bug/1386363
http://bugs.mysql.com/bug.php?id=68460
http://bugs.mysql.com/bug.php?id=67879
http://bugs.mysql.com/bug.php?id=70307

Unfortunately, the syntax for the non-blocking SHOW SLAVE STATUS varies.

http://dev.mysql.com/doc/refman/5.7/en/show-slave-status.html
http://www.percona.com/doc/percona-server/5.6/reliability/show_slave_status_nolock.html
http://www.percona.com/doc/percona-server/5.5/reliability/show_slave_status_nolock.html
http://www.percona.com/doc/percona-server/5.1/reliability/show_slave_status_nolock.html

**Comment by solomonty** [comment]
The feature is no longer needed. The bug was fixed in MySQL 5.6.23.

**Comment by ehammond** [comment]
@solomonty Thanks for following up!
