### ISSUE TITLE
Add ability to add tag name

### ISSUE THREAD

**Issue by airforceboricua** [alestic/ec2-consistent-snapshot#51]
Please add the ability to add the tag='Name'.

**Comment by PortableTech** [comment]
I am a little confused on this one as the change log shows the addition of the --tags option, but it does not seem to work in my testing.  Can anyone clarify if this is supposed to work?

**Comment by ehammond** [comment]
I tested this with the latest version of ec2-consistent-snapshot and it worked for me.

You will need to make sure that the active IAM user or role has permission to create tags on the snapshot.

It is odd that the --tag option is not documented in the man page. I'd love to see this added.
