### ISSUE TITLE
Request for ability to cleanup old snapshots

### ISSUE THREAD

**Issue by wilrnh** [alestic/ec2-consistent-snapshot#53]
Perhaps a --retention=n option that lists the snapshots for each volume-id and deletes the oldest snapshots post-thaw.

Currently, I'm using a custom script via the --post-thaw-command, but this is inconvenient, as I need to duplicate the volume-ids.

I could work on a PR, but I'm not a perl guru yet. And I  just wanted to get this out there for comments.

**Comment by ehammond** [comment]
The job of ec2-consistent-snapshot is to create snapshots. I don't accept PR's to delete volumes in this project.

There is an ec2-expire-snapshots project where you are also welcome to suggest and submit enhancements.
