### ISSUE TITLE
How to do this at scale ?

### ISSUE THREAD

**Issue by abhiofdoon** [alestic/ec2-consistent-snapshot#61]
From my understanding, this script needs to be installed on each instance.
Is that correct ?

If so how can we do this at scale if we have several servers which needs to be snapshotted ?

Thanks

**Comment by ehammond** [comment]
I'd recommend installing ec2-consistent-snapshot using the same automated process you use to install other software on your instances, whether it be user-data scripts, ansible, puppet, chef, opsworks, or whatever.

Note that you no longer need to specify individual volume ids as ec2-consistent-snapshot can look these up for you based on the file systems you specify on the command line.
