### ISSUE TITLE
feature request - tag and purge backups

### ISSUE THREAD

**Issue by slikk66** [alestic/ec2-consistent-snapshot#64]
Similar to functionality in https://github.com/colinbjohnson/aws-missing-tools/tree/master/ec2-automate-backup

Add parameters to tag volumes for backup purge on creation, followed by parameter to then purge volumes with those tags.

This allows a single script to handle entire backup process.

Major advantage for this script is fact it freezes file system.

**Comment by ehammond** [comment]
ec2-consistent-snapshot supports setting tags on the created snapshots.

ec2-consistent-snapshot does not and will not support the actual expiring and deleting of snapshots. Those functions are available in orthogonal tools that specialize in such.

One of, I'm sure, many is https://github.com/alestic/ec2-expire-snapshots
