### ISSUE TITLE
--tag option is not documented

### ISSUE THREAD

**Issue by markstos** [alestic/ec2-consistent-snapshot#66]
The --tag option is not documented in either the online help or published README.

This leads to people requesting that the feature be added although it already exists, most recently as in #64.

I'll volunteer to add the documentation. I was surprised to find there is support for applying the same tag to every instance, to apply multiple tags per instance, and also to apply different tags for each snapshot. 

I just submitted pull request #65, which will confirm which tags are getting applied to which snapshots. 

If that PR is excepted, I might reference it in the documentation for `--tag`.

**Comment by markstos** [comment]
I've updated PR #65 with a new commit which documents the --tag option.

https://github.com/markstos/ec2-consistent-snapshot/commit/126b73e629e7d3cae3a52e111f9a8ccc84a7f70a

The new text could use a peer-review for correctness.

**Comment by ehammond** [comment]
I think this was completed a while ago.
