### ISSUE TITLE
Intended OS / distro support?

### ISSUE THREAD

**Issue by markstos** [alestic/ec2-consistent-snapshot#70]
As I look at trying to improve some issues I've found here, it would be helpful to know what the intended OS and distro support is. Distros differ in whether they are using the Upstart, systemd or "SysV init" scripts, and where binaries end up getting stored.  

Because of the restricted PATH setting that cron has, it would be a convenience to check some paths that the OS does not check by default (like looking for `fsfreeze` in `/sbin/` and `/usr/sbin/`, which are not in the cron default PATH).   

Even just looking at Ubuntu, there is the transition from SysV Init -> Upstart -> systemd that has happened over time.

**Comment by markstos** [comment]
Perhaps the disclaimer from [alestic.com](https://alestic.com/about/) applies here?

> Unless specified, sample commands in this blog are generally tested on the latest LTS (Long Term Support) release of Ubuntu. Instructions may work on other Linux distros like Amazon Linux, Debian, or CentOS, but may also need some adaptation.

Assuming this could simplify some of my proposed improvements.

**Comment by ehammond** [comment]
Yep. I'd say that pretty much sums up my laziness. I want it to work for me, but am happy to pull things in if somebody else puts in effort to get it to work elsewhere.
