### ISSUE TITLE
read_mydefaultsfile() fails to parse properly when single quotes are used

### ISSUE THREAD

**Issue by solomonty** [alestic/ec2-consistent-snapshot#73]
`read_mydefaultsfile()` only handles the cases where there are no quotes or double quotes surrounding the value.

https://github.com/alestic/ec2-consistent-snapshot/blob/master/ec2-consistent-snapshot#L809-L816

**Comment by solomonty** [comment]
Use `Config::Simple` to parse the config file?

**Comment by solomonty** [comment]
or MySQL::Config?

**Comment by ehammond** [comment]
Excellent ideas! Clean, tested pull requests welcomed.

**Comment by ehammond** [comment]
Thanks for submitting this. Unfortunately, this project is no longer under development in this repo. Anybody is welcome to fork the project and continue development if there is interest.
