### ISSUE TITLE
Support for longer format snapshot IDs

### ISSUE THREAD

**Issue by markdwhite** [alestic/ec2-consistent-snapshot#74]
Looks like the dependency here is on Net::Amazon::EC2, with the ec2-consistent-snapshot script using 0.11, with current at 0.31 from Sep 2015 which was from before the longer format snapshot IDs (and others) were announced.

https://aws.amazon.com/ec2/faqs/#longer-ids

Does this mean ec2-consistent-snapshot will break with long format IDs, or should I be aiming this question to the Net::Amazon::EC2 maintainer?

Thanks.

**Comment by ehammond** [comment]
@markdwhite Are you saying that ec2-consistent-snapshot does not currently support long snapshot ids?

What is the specific message or result when you try to use it in an account that has this turned on?

**Comment by markdwhite** [comment]
@ehammond 

I'm asking whether ec2-consistent-snapshot will break with long format IDs given the AWS FAQ does not mention whether Net::Amazon::EC2 is compliant with long format IDs and the current version of that library used by ec2-consistent-snapshot seems quite old. 

It's not enabled yet, given this is in use in production and it's not something I want to willingly break without asking first.

**Comment by markdwhite** [comment]
@ehammond 

Did a test on a spare AWS account where I could test long format IDs without breaking anything, and get this error:

sudo ./ec2-consistent-snapshot --aws-access-key-id XXXXXXXXXXXXXXXXXX --aws-secret-access-key XXXXXXXXXXXXXXXXXXXXXXX vol-09e0d458350XXXX

ec2-consistent-snapshot: ERROR: create_snapshot: InvalidVolumeID.Malformed: Invalid id: "vol-09e0d458350XXXX" at ./ec2-consistent-snapshot line 323.

This is where it's calling $ec2->create_snapshot() so does this mean the Net::Amazon::EC2 library is the problem here?

**Comment by ehammond** [comment]
@markdwhite We are using ec2-consistent-snapshot v0.67 to generate snapshots with long-form ids and aren't seeing any errors. We appear to be using Net::Amazon::EC2 version 0.31.

The dependency should be for Net::Amazon::EC2 version 0.11 or higher. Apparently something higher is needed for long-form snapshot ids.

I don't plan to change the dependency as it is still usable in AWS accounts without the longer form ids turned on, but you should upgrade if you have it enabled.

**Comment by markdwhite** [comment]
@ehammond  

Got it. Using Ubuntu 14.04 here, which installs Net::Amazon::EC2 v0.24 by default, but upgrading to 0.31 via CPAN solves the problem.
