### ISSUE TITLE
LVM Thin Volumes in CentOS 7 do not work with the current Volume ID detection logic

### ISSUE THREAD

**Issue by tavisma** [alestic/ec2-consistent-snapshot#77]
I am trying to use ec2-consistent-snapshot on a CentOS 7 server with and an LVM thin volume 
The ec2-consistent-snapshot script is unable to determine the volume id for the partition

Looking at the detection logic its not designed to deal with the multiple levels of indirection to find the actual underlying device

**Comment by campus-explorer-system** [comment]
@tavispaquette 

Thanks for reporting this.

I would welcome simple pull requests that enhance the logic to take care of this situation without breaking working volume detection.

**Comment by tavispaquette** [comment]
Sure, i'll work on getting you a PR for this environment

I put something together that worked but it was an abomination so i'll see if i can find a better approach

**Comment by tavispaquette** [comment]
Okay, i'll be submitting a PR shortly
I'm not entirely happy with the code but i've tested it with standard block devices, RAID/MD volumes, LVM volumes and LVM thin volumes and it behaves as expected

**Comment by tavispaquette** [comment]
Refer to: https://github.com/alestic/ec2-consistent-snapshot/pull/79
