### ISSUE TITLE
wish: auto-retry when "503 Service Unavailable" is returned. 

### ISSUE THREAD

**Issue by markstos** [alestic/ec2-consistent-snapshot#80]
Last night my snapshot made with this tool failed with:

> Amazon EC2 Errors [Request N/A]:
> [HTTP POST FAILURE] 503 Service Unavailable

I'm not sure which call triggered it, but it would be nice if basic auto-retry functionality was built in when a recoverable error like 503 is returned.

**Comment by ehammond** [comment]
Thanks for submitting this. Unfortunately, this project is no longer under development in this repo. Anybody is welcome to fork the project and continue development if there is interest.
