### ISSUE TITLE
replace experimental --mongo-stop with more flexible solution

### ISSUE THREAD

**Issue by markstos** [alestic/ec2-consistent-snapshot#83]
The --mongo-stop solution currently only works with SysVinit-style process management scripts.  It works in tandem with the `--mongo-init` script, which refers to a command that can be passed the `stop` and `start` subcommands. 

Unfortunately, on SysVInit scripts work that way, while just on Ubuntu 14.04 and 16.04, Upstart-style and `systemd` style control are also used. Here are what the different syntaxes might look like:

```
  # SysV
 /etc/init.d/mongod stop 

# Upstart
start mongod

# systemd
systemctl start mongod
```

There's also inconsistency about whether the MongoDB service is named 'mongod' or 'mongodb'. 

To make things more interesting, the MongoDB lcoud manager manages it's own version of `mongod` and that service is named `mongodb-mms-automation-agent.service`

Since all three init systems allow us to check the status of a service, so **we could check a number options across the different init systems to provide a "just works" solution for --mongo-stop.**

To override that default dehavior, you could provide a  `--mongo-service` option, which would provide a systemd service name to stop/start.  `--mongo-init` already covers the `SysVinit` case exclusively, and I think there's not need to provide an Upstart-specific solution. Any OS version which supports Upstart also supports SysVinit scripts or `systemd`.

**Comment by ehammond** [comment]
Thanks for submitting this. Unfortunately, this project is no longer under development in this repo. Anybody is welcome to fork the project and continue development if there is interest.
