### ISSUE TITLE
mysql percona support: add 'LOCK BINLOG FOR BACKUP'

### ISSUE THREAD

**Issue by danielbeardsley** [alestic/ec2-consistent-snapshot#86]
Looks like Percona supports locking the binlog so we *can* get the `MASTER STATUS` in a safe manner even when using the `--percona` option.

See this Percona blog post.
https://www.percona.com/blog/2014/03/11/introducing-backup-locks-percona-server-2/

**Comment by ehammond** [comment]
Thanks for submitting this. Unfortunately, this project is no longer under development in this repo. Anybody is welcome to fork the project and continue development if there is interest.
