### ISSUE TITLE
--signature-version option is undocumented

### ISSUE THREAD

**Issue by markstos** [alestic/ec2-consistent-snapshot#88]
[This commit](https://github.com/alestic/ec2-consistent-snapshot/commit/d22a0cb72e00ef25dbf745139aead97aca29649f) added support for a --signature-version option, but it is documented. 

As noted in #87, sometimes the changing signature version can be essential for getting the tool to work in a region.

I'll look at adding this documentation.

**Comment by ehammond** [comment]
Thanks for submitting this. Unfortunately, this project is no longer under development in this repo. Anybody is welcome to fork the project and continue development if there is interest.
