### ISSUE TITLE
strange problem when flushing database

### ISSUE THREAD

**Issue by viyullas** [alestic/ec2-consistent-snapshot#89]
Hello!
We are experiencing a very sdtrange problem when using ec2-consistent-snapshot with a mysql db on a non root volume.
The worst thing is sometimes the script ends OK and other times not.

Here is the output from one of the faied executions:

.ec2-consistent-snapshot/ec2-consistent-snapshot -d --aws-credentials-file /root/.ec2/melga/awssecret --region eu-west-1 --freeze-filesystem /vol --mysql --mysql-defaults-file /root/.mysql-connection-info --mysql-master-status-file /vol/mysql-master.status --lock-timeout 1 --description TEMPdb vol-087f658c149efsd34
ec2-consistent-snapshot: Using AWS access key: XXXXXXXXXXXXXXXX
ec2-consistent-snapshot: Using description 'TEMPdb' for all snapshot descriptions
ec2-consistent-snapshot: Mon Jan 23 12:35:59 2017: MySQL connect as root
ec2-consistent-snapshot: Mon Jan 23 12:35:59 2017: MySQL flush
ec2-consistent-snapshot: MySQL timeout at 1 sec
ec2-consistent-snapshot: Trying again in 5 seconds
ec2-consistent-snapshot: Mon Jan 23 12:36:05 2017: MySQL flush
DBD::mysql::db do failed: Query execution was interrupted at ec2-consistent-snapshot/ec2-consistent-snapshot line 758.
ec2-consistent-snapshot: Mon Jan 23 12:36:05 2017: MySQL flush & lock
ec2-consistent-snapshot: MySQL timeout at 1 sec
ec2-consistent-snapshot: Trying again in 5 seconds
ec2-consistent-snapshot: Mon Jan 23 12:36:11 2017: MySQL flush & lock
DBD::mysql::db do failed: Query execution was interrupted at ec2-consistent-snapshot/ec2-consistent-snapshot line 758.
DBD::mysql::db selectrow_hashref failed: fetch() without execute() at ec2-consistent-snapshot/ec2-consistent-snapshot line 674.
DBD::mysql::db selectrow_array failed: fetch() without execute() at ec2-consistent-snapshot/ec2-consistent-snapshot line 683.
ec2-consistent-snapshot: Mon Jan 23 12:41:59 2017: sync
ec2-consistent-snapshot: Mon Jan 23 12:41:59 2017: fsfreeze -f /vol
ec2-consistent-snapshot: Mon Jan 23 12:41:59 2017: create EC2 object
ec2-consistent-snapshot: Endpoint: https://ec2.eu-west-1.amazonaws.com
ec2-consistent-snapshot: volume_id: vol-087f658c149eb9f22; description: TEMPdb
ec2-consistent-snapshot: Mon Jan 23 12:41:59 2017: aws ec2 create-snapshot vol-087f658c149efsd34
snap-0029d85cfxxxxxxx
ec2-consistent-snapshot: Mon Jan 23 12:41:59 2017: fsfreeze -u /vol
ec2-consistent-snapshot: Mon Jan 23 12:41:59 2017: removing master info file: /vol/mysql-master.status
ec2-consistent-snapshot: Couldn't remove file: /vol/mysql-master.status: No such file or directory
END failed--call queue aborted at ec2-consistent-snapshot/ec2-consistent-snapshot line 228.

We have the same working on another machine (gentoo) without any problem but in our new server (debian) we are not able to make it run smooth.

**Comment by awaage** [comment]
I am running into a similar issue. Did you ever figure out why? thanks in advance @viyullas

**Comment by viyullas** [comment]
No, sorry.
We started using another tool.

**Comment by tomgpoole** [comment]
@viyullas may I ask what the other tool is?

**Comment by ehammond** [comment]
Thanks for submitting this. Unfortunately, this project is no longer under development in this repo. Anybody is welcome to fork the project and continue development if there is interest.
