### ISSUE TITLE
MySQL replica coordinates

### ISSUE THREAD

**Issue by ggunson** [alestic/ec2-consistent-snapshot#92]
No idea if this is still being worked on, but in https://github.com/alestic/ec2-consistent-snapshot/blob/master/ec2-consistent-snapshot#L716 there's

```perl
    # This might be a slave database already
    my $slave_status = $mysql_dbh->selectrow_hashref(q{ SHOW SLAVE STATUS });
    $mysql_logfile           = $slave_status->{Slave_IO_State}
                             ? $slave_status->{Master_Log_File}
                             : undef;
    $mysql_position          = $slave_status->{Read_Master_Log_Pos};
    $mysql_binlog_do_db      = $slave_status->{Replicate_Do_DB};
    $mysql_binlog_ignore_db  = $slave_status->{Replicate_Ignore_DB};
```

The replica's replication coordinates, in terms of what place in the master binary log its data is caught up to, would actually be

> Relay_Master_Log_File
> Exec_Master_Log_Pos

instead of 

> Master_Log_File
> Read_Master_Log_Pos

The coordinates you're using are the coordinates for the IO thread, in terms of what binlogs it's currently copying from the master. The relay_master_log_file/exec_master_log_pos are the coordinates for the SQL thread, which is actually writing the changes to the data. In a busy system, these aren't always going to be the same thing and you'll end up creating a snapshot that points to the wrong binlog and position when restored.

https://dev.mysql.com/doc/refman/5.7/en/show-slave-status.html

**Comment by ehammond** [comment]
Thanks for submitting this. Unfortunately, this project is no longer under development in this repo. Anybody is welcome to fork the project and continue development if there is interest.
