### ISSUE TITLE
Can't take snapshots of the volumes for mongo setup with authentication

### ISSUE THREAD

**Issue by sameergautam** [alestic/ec2-consistent-snapshot#93]
I have a Mongo server set up in AWS. The data directory of the Mongo server is laid upon the `lvm` whose physical volumes comprise of the RAID 0 devices. The Mongo server is setup with authentication. Since there are multiple devices involved and I'd like to make the snapshot process as automated as possible ( to run it as cron), I've built a shell script as below:

```
#!/bin/bash

#consistent snapshot of the volumes other than /dev/sda1 or /dev/xvda1

EC2_INSTANCE_ID=$(grep instance-id /tmp/ec2-selfmeta | awk -F: '{print $2}')

aws ec2 describe-volumes --filters Name=attachment.instance-id,Values=`echo $EC2_INSTANCE_ID` --region us-west-1 --output=text | grep ATTACHMENTS | grep -v /dev/sda1 | cut -f7 > ./vol_info_create.txt

# Iterate through the volumes of which the snapshots are to be taken
while read line
    do
        EC2_VOL_ID=$line
        /usr/bin/ec2-consistent-snapshot --use-iam-role --noaction --debug --mongo --mongo-username my_mongo_user --mongo-password my_super_secret_password --freeze-filesystem /data --xfs-filesystem /data --region us-west-1 `echo $EC2_VOL_ID` --description "$(hostname) snapshot  $(date +'%Y-%m-%d %H:%M:%S') of `echo $EC2_VOL_ID`"
    done < ./vol_info_create.txt
```

I could easily connect to Mongo via the username/password in the script (redacted here). However, I'm getting the following error while taking the snapshots:

<details>
<summary>Error while taking snapshots</summary>

```
ec2-consistent-snapshot: Authenticating with IAM role

ec2-consistent-snapshot: Using description 'mongo-server1 snapshot  2017-07-05 09:02:29 of volume_id1' for all snapshot descriptions

ec2-consistent-snapshot: Wed Jul  5 09:02:30 2017: mongo connect on localhost:27017
Can't locate object method "authenticate" via package "MongoDB::MongoClient" at /usr/bin/ec2-consistent-snapshot line 529.

ec2-consistent-snapshot: Wed Jul  5 09:02:30 2017: done

ec2-consistent-snapshot: Authenticating with IAM role

ec2-consistent-snapshot: Using description 'mongo-server1 snapshot  2017-07-05 09:02:30 of volume_id2' for all snapshot descriptions

ec2-consistent-snapshot: Wed Jul  5 09:02:31 2017: mongo connect on localhost:27017
Can't locate object method "authenticate" via package "MongoDB::MongoClient" at /usr/bin/ec2-consistent-snapshot line 529.

ec2-consistent-snapshot: Wed Jul  5 09:02:31 2017: done
```

</details> 

Has anyone ever encountered this? Please help me get out of this quicksand.
Any help is much appreciated.

**Comment by ehammond** [comment]
Take a look at https://github.com/alestic/ec2-consistent-snapshot/issues/72 and https://github.com/alestic/ec2-consistent-snapshot/pull/82

Also, you aren't going to get a consistent snapshot across an LVM group unless you specify all of the EBS volume ids on the command line in the same invocation.

**Comment by sameergautam** [comment]
Thanks @ehammond for reviewing my script as well. As mentioned in [#72](https://github.com/alestic/ec2-consistent-snapshot/issues/72), I tried installing the `libmongodb-perl` package, but it is already in its latest version and I fear to lock the db. Any way around this ?

**Comment by markstos** [comment]
@sameergautam If you are using journaling, you don't need to use the Mongo-specific methods to lock the database, you can just a filesystem "freeze" command, as is available in `ext4`, `xfs` and others. This method is officially endorsed by MongoDB:

https://docs.mongodb.com/manual/tutorial/backup-with-filesystem-snapshots/#backup-with-journaling

**Comment by markstos** [comment]
With no further comments from the OP, I assumed my last comment addressed the issue and am closing this.
