### ISSUE TITLE
Attribute (code) does not pass the type constraint because: Validation failed for 'Int|Str' with value undef at constructor Net::Amazon::EC2::StateReason::new (defined at /usr/share/perl5/Net/Amazon/EC2/StateReason.pm line 31) 

### ISSUE THREAD

**Issue by markstos** [alestic/ec2-consistent-snapshot#94]
It's possible for backups to fail  with this error:

```
Attribute (code) does not pass the type constraint because: Validation failed for 'Int|Str' with value undef at constructor Net::Amazon::EC2::StateReason::new (defined at /usr/share/perl5/Net/Amazon/EC2/StateReason.pm line 31) 
```

This is due to [a bug in Net::Amazon::EC2](https://github.com/mrallen1/net-amazon-ec2/pull/54). The issue has been fixed upstream in that Git repo and is currently pending release.

Note that bumping the version of `Net::Amazon::EC2` that we depend on will also resolve #76.  Both issues should reviewed as part of a dependency bump. 

The immediate workaround for this issue is use the latest version of Net::Amazon::EC2 from Git (untested).

**Comment by markstos** [comment]
Net::Amazon::EC2 has released 0.33, so we are cleared to update our dependency.

**Comment by markstos** [comment]
Not so fast., we don't depend on the Perl module directly, but on a Ubuntu package which provides the Perl module. I have filed a bug to ask Ubuntu update their package of the Perl module:

https://bugs.launchpad.net/ubuntu/+source/libnet-amazon-ec2-perl/+bug/1739294

**Comment by markstos** [comment]
I'm not using a Bash-based version as an alternative: https://github.com/RideAmigosCorp/ec2-consistent-snapshot.sh

**Comment by macropin** [comment]
Net::Amazon::EC2 0.35 seems to be a good version. But I agree this utility has a better future as a bash script.

**Comment by ehammond** [comment]
Thanks for submitting this. Unfortunately, this project is no longer under development in this repo. Anybody is welcome to fork the project and continue development if there is interest.
