### ISSUE TITLE
ERROR: The volume 'vol-xxx' does not exist.

### ISSUE THREAD

**Issue by bogdanr** [alestic/ec2-consistent-snapshot#95]
This is the error I am getting:

```
ec2-consistent-snapshot: Using AWS access key: xxx
ec2-consistent-snapshot: Using default snapshot description
ec2-consistent-snapshot: Using description 'ec2-consistent-snapshot' for all snapshot descriptions
ec2-consistent-snapshot: Using tag 'Name=admindb-data' for all snapshot tags
ec2-consistent-snapshot: Mon Jan 29 02:20:42 2018: MySQL connect as root
ec2-consistent-snapshot: Mon Jan 29 02:20:42 2018: MySQL flush
ec2-consistent-snapshot: Mon Jan 29 02:20:42 2018: MySQL flush & lock
ec2-consistent-snapshot: master_log_file="mysql-bin.083928", master_log_pos=191506842
ec2-consistent-snapshot: Mon Jan 29 02:20:42 2018: sync
ec2-consistent-snapshot: Mon Jan 29 02:20:42 2018: create EC2 object
ec2-consistent-snapshot: volume_id: vol-0ffc8e118b4f1342a; description: ec2-consistent-snapshot
ec2-consistent-snapshot: Mon Jan 29 02:20:42 2018: aws --region eu-west-1 ec2 create-snapshot --volume-id vol-0ffc8e118b4f1661a --output text
ec2-consistent-snapshot: ERROR: The volume 'vol-0ffc8e118b4f1342a' does not exist.
ec2-consistent-snapshot: Mon Jan 29 02:20:42 2018: MySQL unlock
ec2-consistent-snapshot: Mon Jan 29 02:20:42 2018: MySQL disconnect
ec2-consistent-snapshot: Mon Jan 29 02:20:42 2018: done

dbadmin@admin:~$ aws --region eu-west-1 ec2 create-snapshot --volume-id vol-0ffc8e118b4f1342a --output text
None	False	634260008656	None	snap-01a7754e8f344de3f	2018-01-29T10:21:32.000Z	pending	vol-0ffc8e118b4f1342a	1500
```

As you can see, if I run the `aws ec2 create-snapshot` command, it does what it should.

**Comment by markstos** [comment]
The output says we are using `aws ec2 create-snapshot`, but we are actually using Net::Amazon::EC2 Perl Module, and the problem would be related to that.  You should include the version of Net::Amazon::EC2 installed on your system. Sometimes this works to find it: `perldoc -l Net::Amazon::EC2 | grep VERSION`.  Also try installing the latest version of that module and see it helps.

    sudo cpan -i Net::Amazon::EC2

See the related code here:

    https://github.com/alestic/ec2-consistent-snapshot/blob/ecd9e9febc7cf1cfb6f9e48a49446ec8d1436849/ec2-consistent-snapshot#L310

**Comment by bogdanr** [comment]
I ran `cpan -i` and now it's up to date `Net::Amazon::EC2 is up to date (0.35).` but I still get an error, even though it's slightly different:
`ERROR: create_snapshot: InvalidVolume.NotFound: The volume 'vol-0ffc8e118b4f1342a' does not exist. at /root/ec2-consistent-snapshot-master/ec2-consistent-snapshot line 325.`

**Comment by markstos** [comment]
@bogdanr Are you using role-based authentication? Perhaps this is related to https://github.com/alestic/ec2-consistent-snapshot/issues/76

Next, I would try to reproduce the issue using only `Net::Amazon::EC2` to determine if the issue is what that module, or if there is a logic problem in `ec2-consistent-snapshot`

**Comment by bogdanr** [comment]
I am using just a regular IAM user which has propper rights. This used to work one year ago but at some point it stopped working. Updating ec2-consistent-snapshot and the cpan module you suggested didn't help.

I am not sure how I could reproduce using only `Net::Amazon::EC2`.

**Comment by markstos** [comment]
@bogdanr, it should be something like this:

```perl
#!/usr/bin/env perl

use Net::Amazon::EC2;
 
my $ec2 = Net::Amazon::EC2->new(
       AWSAccessKeyId    => 'PUBLIC_KEY_HERE', 
       SecretAccessKey   => 'SECRET_KEY_HERE',
       signature_version => 4,
);
 
my $snapshot = $ec2->create_snapshot(    VolumeId    => 'VOLUME_ID_GOES_HERE' );

print "Result: snapshot ID: "+$snapshot->snapshot_id+" Error was $@\n";
```
(That's untested.)

**Comment by bogdanr** [comment]
It returns this:
```
Amazon EC2 Errors [Request 344c8285-0d45-41b9-bd9d-0a67604d660e]:
[InvalidVolume.NotFound] The volume 'vol-0ffc8e118b4f1342a' does not exist.
```

**Comment by markstos** [comment]
In the `new` constructor, you'll also need to add:

     region => 'eu-west-1',

Sorry, it defaults to `us-east-1` and I didn't mention that the first time.

**Comment by bogdanr** [comment]
The test script worked now.

**Comment by markstos** [comment]
Try removing `signature_version => 4` from the test script. Does it start failing again? 

If so, does adding `--signature-version=4` to your `ec2-consistent-snapshot` command line fix your issue?

**Comment by bogdanr** [comment]
If I remove that from the test script, it still works and adding the parameter to `ec2-consistent-snapshot` doesn't help.

**Comment by markstos** [comment]
OK, so the debugging so far points to `ec2-consistent-snapshot` not passing the right arguments to `Net::Amazon::EC2`. Try adding the `--debug` option to `ec2-consistent-snapshot`. This also enables debugging `Net::Amazon::EC2`. If that doesn't clarify the issue, post the output here, redacting anything you need to.

**Comment by bogdanr** [comment]
The first output I sent is what is produced when `--debug` is used.

**Comment by markstos** [comment]
That was before you upgraded to Net::Amazon::EC2 to 0.35.

**Comment by bogdanr** [comment]
```
ec2-consistent-snapshot: Using AWS access key: xxx
ec2-consistent-snapshot: Using default snapshot description
ec2-consistent-snapshot: Using description 'ec2-consistent-snapshot' for all snapshot descriptions
ec2-consistent-snapshot: Using tag 'Name=admindb-data' for all snapshot tags
ec2-consistent-snapshot: Tue Jan 30 08:02:02 2018: MySQL connect as root
ec2-consistent-snapshot: Tue Jan 30 08:02:02 2018: MySQL flush
ec2-consistent-snapshot: Tue Jan 30 08:02:02 2018: MySQL flush & lock
ec2-consistent-snapshot: master_log_file="mysql-bin.084077", master_log_pos=197130752
ec2-consistent-snapshot: Tue Jan 30 08:02:02 2018: sync
ec2-consistent-snapshot: Tue Jan 30 08:02:02 2018: create EC2 object
ec2-consistent-snapshot: volume_id: vol-0ffc8e118b4f1342a; description: ec2-consistent-snapshot
ec2-consistent-snapshot: Tue Jan 30 08:02:02 2018: aws ec2 create-snapshot vol-0ffc8e118b4f1342a
ec2-consistent-snapshot: ERROR: create_snapshot: InvalidVolume.NotFound: The volume 'vol-0ffc8e118b4f1342a' does not exist. at /root/ec2-consistent-snapshot-master/ec2-consistent-snapshot line 325.
ec2-consistent-snapshot: Tue Jan 30 08:02:03 2018: MySQL unlock
ec2-consistent-snapshot: Tue Jan 30 08:02:03 2018: MySQL disconnect
ec2-consistent-snapshot: Tue Jan 30 08:02:03 2018: done
```

**Comment by markstos** [comment]
Did you remember to include `--region eu-west-1` ? It appears in the debug output of your first debug file you posted, but not this one.

**Comment by bogdanr** [comment]
I am very sorry for wasting your time! 😞 
It seems at some point after the upgrade I accidentally removed that parameter. After adding it, all works as expected.

Thanks a lot for your help! I really appreciate it! 🙇

**Comment by bogdanr** [comment]
I think the best options are:
- Persuade the package maintainers to update the package. I also sent a mail to the 3 Debian maintainers.
- Rewrite to use a better dependency; Maybe even rewrite in python because the python SDK feels better supported?!

**Comment by markstos** [comment]
@bogdanr, "Paws" is considered the more supported Perl dependency for AWS, I think. (reference: https://aws.amazon.com/blogs/developer/hello-perl-developers/ ) 

Rewrites to use Paws or even a Python rewrite I think would be welcome by the maintainers, but neither of us have the incentive to take on these projects, as the current version works well enough for us.

The thing is,  Net::Amazon::EC2 works 0.35 works fine, it's just managing the dependency that's a problem at the moment.

I might be inclined to try switching the distribution method to CPAN. That would support non-Ubuntu distributions better.

On the other hand, Perl is less popular than it used to be, and I realize for system managers that it's easier to deal with native OS packages.

**Comment by ablundgren** [comment]
The newer depend has broken this tool on Amazon linux.  The newest version that is available in an RPM on AWS linux-1 is:
erl-Net-Amazon-EC2.noarch                                                                 0.29-1.3.amzn1

**Comment by markstos** [comment]
Amazon Linux is not officially supported, but we are starting to package the app as a "snap". That's supported by lots of distributions, but Amazon Linux is not one of them. You can search the issue tracker for "snap" for more about that. 

Alternatively, you can try to manually apply this patch to the copy of Net/Amazon/EC2 you already have on your file system:

https://patch-diff.githubusercontent.com/raw/mrallen1/net-amazon-ec2/pull/54.diff

Finally, "AWS Linux 2" has already been released. Consider checking that newer operating system for newer packages.

**Comment by ablundgren** [comment]
We are doing some things directly on the OS that the changes to the startup system impact, so moving to Amazon Linux 2 isn't as easy as it might seem.

As there is no package for ec2-snapshot, we are downloading the source and building it as we build our AMI.  For now, we are downloading an older snapshot before the update.  We could do the same thing to patch the net-amazon-ec2 package, but I would like not to be any further into that business than I have to.  We only started that for the ec2-snapshot tool when we moved off of debian/ubuntu.

**Comment by markstos** [comment]
I plan to focus on maintaining the `snap` going forward instead of the `.deb` packages. It looks like `snap` is adding (or has added) support for Amazon Linux 2, so at least going forward this will better for you then it does now. 

https://github.com/snapcore/snapd/commit/c4248d32c3dd44e18259613bd054e76f90a7353e
