### ISSUE TITLE
Release for Ubuntu Bionic

### ISSUE THREAD

**Issue by sidprak** [alestic/ec2-consistent-snapshot#97]
Would it be possible to get a release for Ubuntu Bionic? It looks like the Alestic PPA currently only goes up to Ubuntu Yakkety. I'm happy to help orchestrate it if there's something I can do there.

**Comment by markstos** [comment]
@sidprak Please try this snap release:

     snap install ec2-consistent-snapshot --channel=edge --devmode

I built it on Bionic, so your odds of it working should be good. It's my first Snap package, though. It would be nice to improve the "confinement" setting so we don't have to publish it in "devmode". You are welcome to work on that.  However, the permissions it has in devmode are the same as it has in the `.deb` file.

So, it's no less secure, it's just that Snaps enable the possibility of being *more* secure by further limiting the filesystem access of your packages.

**Comment by spither** [comment]
I've tried out the snap (on Ubuntu 18.04) and got the following error:

    Can't locate XML/SAX/Expat.pm in @INC (you may need to install the XML::SAX::Expat module) (@INC contains: /snap/ec2-consistent-snapshot/1/usr/lib/x86_64-linux-gnu/perl-base/ /snap/ec2-consistent-snapshot/1/usr/lib/x86_64-linux-gnu/perl5/5.26/ /snap/ec2-consistent-snapshot/1/usr/share/perl5/ /snap/ec2-consistent-snapshot/1/usr/share/perl/5.26.1/ /snap/ec2-consistent-snapshot/1/usr/lib/x86_64-linux-gnu/perl/5.26/ /snap/ec2-consistent-snapshot/1/usr/lib/x86_64-linux-gnu/perl/5.26.1/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at (eval 846) line 1.
    
    XML::Simple called at /snap/ec2-consistent-snapshot/1/usr/share/perl5/Net/Amazon/EC2.pm line 446.

I've fixed it by rebuilding the snap with the following change:

    diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
    index 82b1191..ee9f29d 100644
    --- a/snap/snapcraft.yaml
    +++ b/snap/snapcraft.yaml
    @@ -23,6 +23,7 @@ parts:
           - xfsprogs
           - perl-base
           - perl-modules
    +      - libxml-sax-expat-perl
           - libnet-amazon-ec2-perl
           - libfile-slurp-perl
           - libwww-perl

Seems to be working fine now - thanks for the great tool.

**Comment by markstos** [comment]
@spither Thanks for the report. This issue was resolved in the 0.71 Snap release.
